src/__tests__/__snapshots__/interpreter.test.js.snap, src/__tests__/builtins.test.js, src/__tests__/interpreter.test.js, src/builtins.js
Reduce has to take a curried function so that it can be easily used
=> fix(reduce-function): make reduce actually usable

commitlint.config.js, package.json, yarn.lock
=> git hooks [#93]

website/siteConfig.js
=> docs(website): enable search

docs/basic_filters.md, src/__tests__/__snapshots__/interpreter.test.js.snap, src/__tests__/interpreter.test.js, src/generators/__tests__/ternary.test.js, src/generators/generator.js, src/generators/ternary.js, src/parsers/__tests__/ternary.test.js, src/parsers/pipe/pipe.js, src/parsers/program.js, src/parsers/ternary.js, src/types.js
=> feat: add ternary operator

src/__tests__/descriptions.test.js, src/parsers/abstract/binaryOperator.js, src/parsers/abstract/listLike.js, src/parsers/additive.js, src/parsers/assignment.js, src/parsers/boolean1.js, src/parsers/boolean2.js, src/parsers/boolean3.js, src/parsers/identifier.js, src/parsers/inputProp.js, src/parsers/lambda.js, src/parsers/multiplicative.js, src/parsers/parentheses.js, src/parsers/projection.js, src/parsers/ternary.js, src/parsers/unaryOperator.js, src/parsers/variable.js
=> feat: add descriptions to parsers

docs/comprehensions.md, src/__tests__/__snapshots__/interpreter.test.js.snap, src/__tests__/interpreter.test.js, src/parsers/__tests__/identifier.test.js, src/parsers/__tests__/listCore.test.js, src/parsers/identifier.js, src/parsers/listCore.js, website/i18n/en.json, website/sidebars.json
=> feat: implement basic comprehension syntax

src/__tests__/builtins.test.js, src/builtins.js
=> feat: add 'has' function

src/__tests__/__snapshots__/interpreter.test.js.snap, src/__tests__/builtins.test.js, src/__tests__/interpreter.test.js, src/builtins.js, src/generators/__tests__/list.test.js, src/generators/__tests__/object.test.js, src/generators/list.js
=> fix: fix spreading strings into arrays

docs/variables.md
=> docs(variables): fix formatting & syntax error

src/__tests__/__snapshots__/interpreter.test.js.snap, src/__tests__/builtins.test.js, src/__tests__/interpreter.test.js, src/builtins.js, src/generators/__tests__/projection.test.js, src/parsers/__tests__/projection.test.js, src/parsers/projection.js, src/types.js
=> feat(projection): support aliases in object projection

website/i18n/en.json, website/siteConfig.js
=> docs: add GitHub link to navbar

docs/functions.md, docs/getting_started.md, docs/setup_webpack.md, docs/variables.md
=> docs: remove syntax highlighting from website

src/__tests__/__snapshots__/interpreter.test.js.snap, src/__tests__/builtins.test.js, src/__tests__/interpreter.test.js, src/builtins.js, src/generators/__tests__/projection.test.js, src/generators/objectProjection.js, src/parsers/__tests__/projection.test.js, src/parsers/projection.js, src/types.js
=> feat: implement fragments in object projections

docs/tutorial.md, website/i18n/en.json, website/sidebars.json, website/siteConfig.js
for review:
```bash
cd website
yarn
yarn start
```
=> docs(website): add tutorial

src/__tests__/whitespace.test.js, src/parsers/crap.js
=> feat: support #comments

website/package.json, website/siteConfig.js, website/yarn.lock
=> Set up google anal

docs/comparison_with_other_languages.md, website/i18n/en.json, website/sidebars.json
=> docs: add page with comparison against alternatives

src/__tests__/__snapshots__/interpreter.test.js.snap, src/__tests__/interpreter.test.js, src/parsers/__tests__/primitives.test.js, src/parsers/primitive.js
=> feat: support single-quote strings

docs/object_projections.md, docs/shebang.md, website/i18n/en.json, website/sidebars.json
=> docs: document object projections

docs/functions.md, src/__tests__/__snapshots__/interpreter.test.js.snap, src/__tests__/descriptions.test.js, src/__tests__/interpreter.test.js, src/parsers/__tests__/mapFunctionCall.js, src/parsers/mapFunctionCall.js, src/parsers/section.js
=> feat: support short syntax for map functions

docs/functions.md, src/__tests__/builtins.test.js, src/builtins.js
=> feat: add entries function

docs/functions.md, src/__tests__/__snapshots__/interpreter.test.js.snap, src/__tests__/builtins.test.js, src/__tests__/interpreter.test.js, src/builtins.js
fixes https://github.com/kantord/emuto/issues/567
=> feat: add parseJSON

src/__tests__/__snapshots__/interpreter.test.js.snap, src/__tests__/interpreter.test.js, src/generators/__tests__/list.test.js, src/generators/__tests__/object.test.js, src/generators/list.js
=> fix: #558 Bug: {...$} is not equal to $

docs/functions.md, src/__tests__/builtins.test.js, src/builtins.js
=> feat: make it possible to count the elements of an object

docs/functions.md, package.json, src/__tests__/__snapshots__/interpreter.test.js.snap, src/__tests__/interpreter.test.js, src/builtins.js, yarn.lock
=> feat: add update function
